import './headless.mjs';
import assert from 'node:assert/strict';
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { PNG } from 'pngjs';
import { worldHarness, done } from './world-harness.mjs';
import { installBermudaModels, startDeferredWaterfront } from '../src/world/BermudaModels.js';
import { installBermudaBlockout } from '../src/world/BermudaBlockout.js';
import { Colliders } from '../src/world/Colliders.js';
import { Material } from '../src/engine/render/Material.js';
globalThis.__assetFile = url => {const b=readFileSync('public'+url);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);};
globalThis.__assetImage = bytes => PNG.sync.read(Buffer.from(bytes));
const H = await worldHarness({width:1280,height:800});
const errors=[]; H.GPU.device.addEventListener('uncapturederror', e=>errors.push(e.error.message));
H.GPU.device.pushErrorScope('validation');
// Isolated native-engine waterfront render; flat ground deliberately isolates asset placement.
const app = {scene:H.scene, terrainData:{heightAt:()=>1.45}, colliders:new Colliders()};
installBermudaBlockout(app);
const progress = [];
app.onWaterfrontProgress = done => progress.push(done);
const pending = installBermudaModels(app);
assert.equal(installBermudaModels(app), pending);
const state = await pending;
assert.deepEqual(progress, [0,1,2,3,4,5]);
assert.deepEqual(state.errors,[]); assert.equal(state.loaded.length,5); assert(state.ready);
await startDeferredWaterfront(app);
assert.equal(state.loaded.length,17);
assert.deepEqual(state.errors,[]);
const {E}=H;
const ground = new E.Mesh(new E.BoxGeometry(100,1,65),new Material({name:'test-ground',color:0xb2b292,roughness:1}));
ground.position.set(-65,0.95,-78); H.scene.add(ground);
const sea = new E.Mesh(new E.PlaneGeometry(400,400).rotateX(-Math.PI/2),new Material({name:'test-sea',color:0x208e9e,roughness:.5}));H.scene.add(sea);
mkdirSync('verification',{recursive:true});
await H.shot('verification/waterfront.png',{pos:[-108,27,-6],target:[-66,2,-58]},2);
await H.shot('verification/houses.png',{pos:[-76,10,-46],target:[-68,4,-70]},2);
await H.shot('verification/dock.png',{pos:[-74,6,-5],target:[-64,1,-17]},2);
await H.GPU.queue.onSubmittedWorkDone();
const validation=await H.GPU.device.popErrorScope();
assert.equal(validation,null,validation?.message); assert.deepEqual(errors,[]);
writeFileSync('verification/metrics.json',JSON.stringify(state.metrics,null,2));
console.log('All seventeen assets rendered with no WebGPU validation errors.');
await done();
