import {BoatModel} from '../src/world/BoatModel.js';
import {WORLD} from '../src/world/WorldLayout.js';
import { TerrainData } from '../src/world/TerrainData.js';
import { applyBermudaBootLook } from '../src/world/BermudaIdentity.js';
import { Vendor } from '../src/game/Vendor.js';
import { FishStand } from '../src/game/FishStand.js';
import { Chandlery } from '../src/game/Chandlery.js';
import './headless.mjs';
import assert from 'node:assert/strict';
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { PNG } from 'pngjs';
import { worldHarness, done } from './world-harness.mjs';
import { installBermudaModels, startDeferredWaterfront } from '../src/world/BermudaModels.js';
import { installBermudaBlockout } from '../src/world/BermudaBlockout.js';
import { Colliders } from '../src/world/Colliders.js';
import { Material } from '../src/engine/render/Material.js';
globalThis.__assetFile = url => {const b=readFileSync('public'+url);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);};
globalThis.__assetImage = bytes => PNG.sync.read(Buffer.from(bytes));
const H = await worldHarness({width:1280,height:800});
const errors=[]; H.GPU.device.addEventListener('uncapturederror', e=>errors.push(e.error.message));
H.GPU.device.pushErrorScope('validation');
let lost=null; H.GPU.device.lost.then(info=>{lost=info.reason;});
// Native engine with actual Bermuda terrain heights; simplified ground/water shading isolates placement.
applyBermudaBootLook({settings:{}});
const app = {scene:H.scene, terrainData:new TerrainData(), colliders:new Colliders()};
Vendor.prototype.loadCharacter = async () => {};
app.game = {stand:new FishStand({scene:app.scene,terrain:app.terrainData,colliders:app.colliders}),chandlery:new Chandlery({scene:app.scene,terrain:app.terrainData,colliders:app.colliders})};
installBermudaBlockout(app);
const progress = [];
app.onWaterfrontProgress = done => progress.push(done);
const pending = installBermudaModels(app);
assert.equal(installBermudaModels(app), pending);
const state = await pending;
assert.deepEqual(progress, [0,1,2,3,4,5]);
assert.deepEqual(state.errors,[]); assert.equal(state.loaded.length,5); assert(state.ready);
await startDeferredWaterfront(app);
assert.equal(state.loaded.length,17);
assert.deepEqual(state.errors,[]);
const {E}=H;
const boat=new BoatModel(); boat.group.position.copy(WORLD.boatDock.position); boat.group.rotation.y=WORLD.boatDock.heading; H.scene.add(boat.group);
const geo=new E.PlaneGeometry(220,220,110,110).rotateX(-Math.PI/2);
const positions=geo.attributes.position;
for(let i=0;i<positions.count;i++) {
 const x=positions.getX(i)-70, z=positions.getZ(i)-80;
 positions.setXYZ(i,x,app.terrainData.heightAt(x,z),z);
}
geo.computeVertexNormals();
const ground = new E.Mesh(geo,new Material({name:'test-ground',color:0xb2b292,roughness:1}));
H.scene.add(ground);
const sea = new E.Mesh(new E.PlaneGeometry(400,400).rotateX(-Math.PI/2),new Material({name:'test-sea',color:0x208e9e,roughness:.5}));H.scene.add(sea);
mkdirSync('verification',{recursive:true});
await H.shot('verification/waterfront.png',{pos:[-108,27,-6],target:[-66,2,-58]},2);
await H.shot('verification/houses.png',{pos:[-76,10,-46],target:[-68,4,-70]},2);
await H.shot('verification/marina.png',{pos:[-104,5,22],target:[-112,2,4]},2);
await H.shot('verification/vendors.png',{pos:[-60,4,-17],target:[-66,2.2,-25]},2);
await H.shot('verification/dock.png',{pos:[-74,6,-5],target:[-64,1,-17]},2);
// Include sustained uploads/render submission in the native check, without claiming iPhone FPS.
for(let i=0;i<120;i++) H.renderFrame();
await H.GPU.queue.onSubmittedWorkDone();
const validation=await H.GPU.device.popErrorScope();
assert.equal(lost,null);
assert.equal(validation,null,validation?.message); assert.deepEqual(errors,[]);
writeFileSync('verification/metrics.json',JSON.stringify(state.metrics,null,2));
console.log('All seventeen assets rendered with no WebGPU validation errors.');
await done();
