import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve(new URL('.', import.meta.url).pathname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const player = read('src/player/Player.js');
const boat = read('src/player/BoatController.js');
const relic = read('src/player/RelicVehicle.js');
const app = read('src/App.js');
const wake = read('src/ocean/MobileWake.js');
const mobile = read('src/mobile/BermudaMobileStable.js');
const fish = read('src/world/Fish.js');
assert.match(player, /mode === 'relic'/);
assert.match(player, /KeyK/);
assert.match(boat, /anchored/);
assert.match(boat, /toggleAnchor/);
assert.match(relic, /Enter RELIC|class RelicVehicle/);
assert.match(relic, /cameraMode/);
assert.match(app, /timeSpeed: 0\.05/);
assert.match(app, /cycleWeather/);
assert.match(wake, /BermudaMobileWake/);
assert.match(mobile, /data-key="ShiftLeft">RUN/);
assert.match(mobile, /data-key="KeyK">ANCH/);
assert.match(fish, /dockZone/);
console.log('world polish assertions passed');
