import { createHash } from 'node:crypto';
import { readFile, readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const dist = path.join(root, 'dist');

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...await walk(full));
    else out.push(full);
  }
  return out;
}

const rel = file => path.relative(dist, file).split(path.sep).join('/');

function isCore(file) {
  if (file === 'index.html' || file === 'manifest.webmanifest') return true;
  if (file === 'ui/keyart-720.jpg' || file === 'ui/keyart.jpg' || file === 'ui/app-icon.svg') return true;
  if (file === 'models/bermuda/mobile-v2/bermuda-dock.glb') return true;
  if (file.startsWith('assets/')) return true;                    // Vite JS/CSS + dynamic chunks
  if (file.startsWith('audio/') && file.endsWith('.ogg')) return true;
  if (file.startsWith('textures/smaa/')) return true;
  if (file.startsWith('clouds/') && !file.endsWith('.md')) return true;
  return false;
}

const files = await walk(dist);
const coreFiles = files.map(rel).filter(isCore).sort();

for (const required of [
  'index.html',
  'manifest.webmanifest',
  'ui/keyart-720.jpg',
  'ui/app-icon.svg',
  'models/bermuda/mobile-v2/bermuda-dock.glb',
]) {
  if (!coreFiles.includes(required)) throw new Error('Offline core is missing: ' + required);
}

const hash = createHash('sha256');
let coreBytes = 0;
for (const file of coreFiles) {
  const full = path.join(dist, file);
  const info = await stat(full);
  coreBytes += info.size;
  hash.update(file);
  hash.update(await readFile(full));
}
const version = hash.digest('hex').slice(0, 12);

const meta = {
  version,
  generatedAt: new Date().toISOString(),
  coreBytes,
  coreFileCount: coreFiles.length,
  guarantee: 'dock-first core gameplay after one completed online install',
};
await writeFile(path.join(dist, 'offline-manifest.json'), JSON.stringify(meta, null, 2) + '\n');

const precache = [...coreFiles, 'offline-manifest.json'];

const sw = `// Generated by scripts/build-offline.mjs. Do not edit dist/sw.js by hand.
const VERSION = ${JSON.stringify(version)};
const CORE_CACHE = 'bermuda-core-' + VERSION;
const RUNTIME_CACHE = 'bermuda-runtime-v1';
const CORE_PATHS = ${JSON.stringify(precache, null, 2)};
const CORE_BYTES = ${coreBytes};

const scoped = p => new URL(p, self.registration.scope).href;

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CORE_CACHE);
    // Cache one-by-one so the error names the exact missing asset instead of an opaque addAll failure.
    for (const path of CORE_PATHS) {
      const url = scoped(path);
      const response = await fetch(new Request(url, { cache: 'reload', credentials: 'same-origin' }));
      if (!response.ok) throw new Error('Offline precache failed: ' + path + ' (' + response.status + ')');
      await cache.put(url, response);
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names
      .filter(name => name.startsWith('bermuda-core-') && name !== CORE_CACHE)
      .map(name => caches.delete(name)));
    await self.clients.claim();
  })());
});

async function coreMatch(request) {
  const cache = await caches.open(CORE_CACHE);
  return cache.match(request, { ignoreSearch: true });
}

async function runtimeMatch(request) {
  const cache = await caches.open(RUNTIME_CACHE);
  return cache.match(request, { ignoreSearch: true });
}

async function cacheRuntime(request, response) {
  if (!response || !response.ok || response.type === 'opaque') return;
  const cache = await caches.open(RUNTIME_CACHE);
  await cache.put(request, response.clone());
}

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      // Atomic app shell: a controlled page always gets the index that belongs to this SW version.
      const index = await coreMatch(scoped('index.html'));
      if (index) return index;
      try {
        return await fetch(request);
      } catch (_) {
        return new Response('Bermuda Simulator is not installed for offline use yet.', {
          status: 503,
          headers: { 'Content-Type': 'text/plain; charset=utf-8' },
        });
      }
    })());
    return;
  }

  event.respondWith((async () => {
    // Versioned core files are cache-first and therefore work with zero network.
    const core = await coreMatch(request);
    if (core) return core;

    // Optional world assets are stale-while-revalidate. Anything the player has already visited
    // becomes available offline without forcing the iPhone to store the whole island at once.
    const cached = await runtimeMatch(request);
    const network = fetch(request).then(async response => {
      await cacheRuntime(request, response);
      return response;
    });

    if (cached) {
      event.waitUntil(network.catch(() => {}));
      return cached;
    }

    try {
      return await network;
    } catch (_) {
      return new Response('', { status: 504, statusText: 'Offline asset not cached' });
    }
  })());
});

self.addEventListener('message', event => {
  if (event.data?.type === 'BERMUDA_OFFLINE_STATUS') {
    const reply = {
      type: 'BERMUDA_OFFLINE_STATUS',
      ready: true,
      version: VERSION,
      coreBytes: CORE_BYTES,
      online: self.navigator?.onLine ?? true,
    };
    if (event.ports?.[0]) event.ports[0].postMessage(reply);
    else event.source?.postMessage(reply);
  }
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});
`;

await writeFile(path.join(dist, 'sw.js'), sw);
console.log(`Offline PWA core: ${coreFiles.length} files, ${(coreBytes / 1024 / 1024).toFixed(1)} MiB, version ${version}`);
