import { createHash } from 'node:crypto';
import { readFile, readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const dist = path.join(root, 'dist');

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...await walk(full));
    else out.push(full);
  }
  return out;
}

const rel = file => path.relative(dist, file).split(path.sep).join('/');

function isCore(file) {
  if (file === 'index.html' || file === 'manifest.webmanifest') return true;
  if (file === 'ui/keyart-720.jpg' || file === 'ui/keyart.jpg' || file === 'ui/app-icon.svg') return true;
  if (file === 'models/bermuda/mobile-v2/bermuda-dock.glb') return true;
  if (file.startsWith('assets/')) return true;
  if (file.startsWith('audio/') && file.endsWith('.ogg')) return true;
  if (file.startsWith('textures/smaa/')) return true;
  if (file.startsWith('clouds/') && !file.endsWith('.md')) return true;
  return false;
}

// Everything the phone build can reasonably use, while excluding the enormous desktop/raw duplicates.
// This is the "whole offline game" for mobile, not the entire 664 MiB art repository.
function isMobileFull(file) {
  if (file === 'sw.js' || file === 'offline-manifest.json') return false;
  if (file.startsWith('models/bermuda/desktop/')) return false;
  if (file.startsWith('models/bermuda/expansion/')) return false;
  if (file.startsWith('models/bermuda/hero/desktop/')) return false;
  if (file.startsWith('models/bermuda/street-life/desktop/')) return false;
  // Legacy unoptimised Bermuda GLBs at the folder root have mobile-v2/v3 replacements.
  if (/^models\/bermuda\/bermuda-[^/]+\.glb$/.test(file)) return false;
  return true;
}

const files = await walk(dist);
const all = files.map(rel).sort();
const coreFiles = all.filter(isCore);
const mobileFullFiles = all.filter(isMobileFull);
const coreSet = new Set(coreFiles);
const fullExtraFiles = mobileFullFiles.filter(file => !coreSet.has(file));

for (const required of [
  'index.html',
  'manifest.webmanifest',
  'ui/keyart-720.jpg',
  'ui/app-icon.svg',
  'models/bermuda/mobile-v2/bermuda-dock.glb',
]) {
  if (!coreFiles.includes(required)) throw new Error('Offline core is missing: ' + required);
}

const info = new Map();
for (const file of mobileFullFiles) {
  const s = await stat(path.join(dist, file));
  info.set(file, s.size);
}

const hash = createHash('sha256');
let coreBytes = 0;
for (const file of coreFiles) {
  const full = path.join(dist, file);
  const size = info.get(file) ?? (await stat(full)).size;
  coreBytes += size;
  hash.update(file);
  hash.update(await readFile(full));
}
for (const file of fullExtraFiles) {
  hash.update(file);
  hash.update(String(info.get(file) || 0));
}
const version = hash.digest('hex').slice(0, 12);
const fullBytes = mobileFullFiles.reduce((sum, file) => sum + (info.get(file) || 0), 0);

const meta = {
  version,
  generatedAt: new Date().toISOString(),
  coreBytes,
  coreFileCount: coreFiles.length,
  fullMobileBytes: fullBytes,
  fullMobileFileCount: mobileFullFiles.length,
  guarantee: 'complete mobile-playable package after FULL OFFLINE READY is shown',
  excluded: 'desktop-only, expansion-source and legacy full-resolution duplicate Bermuda assets',
};
await writeFile(path.join(dist, 'offline-manifest.json'), JSON.stringify(meta, null, 2) + '\n');

const corePrecache = [...coreFiles, 'offline-manifest.json'];
const fileSizes = Object.fromEntries(fullExtraFiles.map(file => [file, info.get(file) || 0]));

const sw = `// Generated by scripts/build-offline.mjs.
const VERSION = ${JSON.stringify(version)};
const CORE_CACHE = 'bermuda-core-' + VERSION;
const FULL_CACHE = 'bermuda-full-mobile-' + VERSION;
const RUNTIME_CACHE = 'bermuda-runtime-v2';
const CORE_PATHS = ${JSON.stringify(corePrecache, null, 2)};
const FULL_EXTRA_PATHS = ${JSON.stringify(fullExtraFiles, null, 2)};
const FULL_EXTRA_SIZES = ${JSON.stringify(fileSizes)};
const CORE_BYTES = ${coreBytes};
const FULL_BYTES = ${fullBytes};
const FULL_FILE_COUNT = ${mobileFullFiles.length};
const FULL_READY_KEY = '__bermuda_full_ready__';

const scoped = p => new URL(p, self.registration.scope).href;

async function postToClients(message) {
  const clients = await self.clients.matchAll({ includeUncontrolled: true, type: 'window' });
  for (const client of clients) client.postMessage(message);
}

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CORE_CACHE);
    for (const path of CORE_PATHS) {
      const url = scoped(path);
      const response = await fetch(new Request(url, { cache: 'reload', credentials: 'same-origin' }));
      if (!response.ok) throw new Error('Offline core failed: ' + path + ' (' + response.status + ')');
      await cache.put(url, response);
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names
      .filter(name =>
        (name.startsWith('bermuda-core-') && name !== CORE_CACHE) ||
        (name.startsWith('bermuda-full-mobile-') && name !== FULL_CACHE)
      )
      .map(name => caches.delete(name)));
    await self.clients.claim();
  })());
});

async function cacheMatch(request) {
  const core = await (await caches.open(CORE_CACHE)).match(request, { ignoreSearch: true });
  if (core) return core;
  const full = await (await caches.open(FULL_CACHE)).match(request, { ignoreSearch: true });
  if (full) return full;
  return (await caches.open(RUNTIME_CACHE)).match(request, { ignoreSearch: true });
}

async function fullStatus() {
  const cache = await caches.open(FULL_CACHE);
  const ready = !!(await cache.match(scoped(FULL_READY_KEY)));
  if (ready) return {
    ready: true, completedBytes: FULL_BYTES, completedFiles: FULL_FILE_COUNT,
    fullBytes: FULL_BYTES, fullFileCount: FULL_FILE_COUNT,
  };

  const keys = await cache.keys();
  const urls = new Set(keys.map(k => new URL(k.url).pathname));
  let completedBytes = CORE_BYTES;
  let completedFiles = CORE_PATHS.length - 1; // manifest isn't part of the mobile payload count
  for (const file of FULL_EXTRA_PATHS) {
    if (urls.has(new URL(scoped(file)).pathname)) {
      completedBytes += FULL_EXTRA_SIZES[file] || 0;
      completedFiles++;
    }
  }
  return { ready: false, completedBytes, completedFiles, fullBytes: FULL_BYTES, fullFileCount: FULL_FILE_COUNT };
}

async function installFullMobile() {
  const cache = await caches.open(FULL_CACHE);
  let status = await fullStatus();
  if (status.ready) return status;

  let completedBytes = status.completedBytes;
  let completedFiles = status.completedFiles;
  await postToClients({ type: 'BERMUDA_OFFLINE_PROGRESS', ...status });

  for (const path of FULL_EXTRA_PATHS) {
    const url = scoped(path);
    if (await cache.match(url, { ignoreSearch: true })) continue;

    const response = await fetch(new Request(url, { cache: 'reload', credentials: 'same-origin' }));
    if (!response.ok) throw new Error('Full offline download failed: ' + path + ' (' + response.status + ')');
    await cache.put(url, response);
    completedBytes += FULL_EXTRA_SIZES[path] || 0;
    completedFiles++;
    await postToClients({
      type: 'BERMUDA_OFFLINE_PROGRESS',
      ready: false,
      completedBytes, completedFiles,
      fullBytes: FULL_BYTES, fullFileCount: FULL_FILE_COUNT,
      current: path,
    });
  }

  await cache.put(scoped(FULL_READY_KEY), new Response(VERSION, { headers: { 'Content-Type': 'text/plain' } }));
  const done = { ready: true, completedBytes: FULL_BYTES, completedFiles: FULL_FILE_COUNT, fullBytes: FULL_BYTES, fullFileCount: FULL_FILE_COUNT };
  await postToClients({ type: 'BERMUDA_OFFLINE_PROGRESS', ...done });
  return done;
}

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      const index = await (await caches.open(CORE_CACHE)).match(scoped('index.html'));
      if (index) return index;
      try { return await fetch(request); }
      catch (_) {
        return new Response('Bermuda Simulator is not installed for offline use yet.', {
          status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' },
        });
      }
    })());
    return;
  }

  event.respondWith((async () => {
    const cached = await cacheMatch(request);
    if (cached) return cached;
    try {
      const response = await fetch(request);
      if (response.ok && response.type !== 'opaque') {
        const cache = await caches.open(RUNTIME_CACHE);
        event.waitUntil(cache.put(request, response.clone()));
      }
      return response;
    } catch (_) {
      return new Response('', { status: 504, statusText: 'Offline asset not cached' });
    }
  })());
});

self.addEventListener('message', event => {
  if (event.data?.type === 'BERMUDA_OFFLINE_STATUS') {
    event.waitUntil((async () => {
      const full = await fullStatus();
      const reply = {
        type: 'BERMUDA_OFFLINE_STATUS',
        coreReady: true,
        version: VERSION,
        coreBytes: CORE_BYTES,
        ...full,
      };
      if (event.ports?.[0]) event.ports[0].postMessage(reply);
      else event.source?.postMessage(reply);
    })());
  }

  if (event.data?.type === 'INSTALL_FULL_OFFLINE') {
    event.waitUntil(installFullMobile().catch(async error => {
      await postToClients({ type: 'BERMUDA_OFFLINE_ERROR', message: String(error?.message || error) });
    }));
  }

  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});
`;

await writeFile(path.join(dist, 'sw.js'), sw);
console.log(
  `Offline PWA: core ${coreFiles.length} files / ${(coreBytes/1048576).toFixed(1)} MiB; ` +
  `full mobile ${mobileFullFiles.length} files / ${(fullBytes/1048576).toFixed(1)} MiB; version ${version}`
);
